image:
  repository: ghcr.io/cnych/gitops-demo
  tag: latest
  pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: ghcr-secret

ingress:
  enabled: true
  ingressClassName: nginx
  path: /
  hosts:
    - devops-demo.k8s.local

resources:
  limits:
    cpu: 50m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 128Mi
